---
name: Build & Release RPM & SRPM packages

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and release as assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build RPM and SRPM packages Fedora latest release
        id: rpm_build_latest
        uses: AnjaloHettiarachchi/rpmbuild@v1.1.0-latest
        with:
          spec_file: "firefox-dev.spec"

      - name: Build RPM and SRPM packages for Fedora 33 release
        id: rpm_build_f33
        uses: AnjaloHettiarachchi/rpmbuild@v1.1.0-f33
        with:
          spec_file: "firefox-dev.spec"

      - name: Create a new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Find release notes from [here](https://www.mozilla.org/en-US/firefox/94.0beta/releasenotes/).
          draft: false
          prerelease: false

      - name: Upload RPM as a release asset built for Fedora latest release
        id: upload_rpm_release_latest
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.rpm_build_latest.outputs.rpm_path }}
          asset_name: ${{ steps.rpm_build_latest.outputs.rpm_name }}
          asset_content_type: ${{ steps.rpm_build_latest.outputs.content_type }}

      - name: Upload SRPM as a release asset built for Fedora latest release
        id: upload_srpm_release_latest
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.rpm_build_latest.outputs.srpm_path }}
          asset_name: ${{ steps.rpm_build_latest.outputs.srpm_name }}
          asset_content_type: ${{ steps.rpm_build_latest.outputs.content_type }}

      - name: Upload RPM as a release asset built for Fedora 33 release
        id: upload_rpm_release_f33
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.rpm_build_f33.outputs.rpm_path }}
          asset_name: ${{ steps.rpm_build_f33.outputs.rpm_name }}
          asset_content_type: ${{ steps.rpm_build_f33.outputs.content_type }}

      - name: Upload SRPM as a release asset built for Fedora 33 release
        id: upload_srpm_release_f33
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.rpm_build_f33.outputs.srpm_path }}
          asset_name: ${{ steps.rpm_build_f33.outputs.srpm_name }}
          asset_content_type: ${{ steps.rpm_build_f33.outputs.content_type }}
